# Generated by Django 4.2.7 on 2023-12-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField()),
                ('import_ts', models.TextField()),
                ('deletions', models.IntegerField()),
                ('creations', models.IntegerField()),
            ],
        ),
    ]
