# Generated by Django 4.2.7 on 2023-12-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataimport',
            options={'ordering': ['run_at', 'import_ts']},
        ),
        migrations.AddConstraint(
            model_name='dataimport',
            constraint=models.UniqueConstraint(models.F('run_at'), models.F('import_ts'), name='unique_run_import_ts'),
        ),
    ]
