# Generated by Django 4.2.6 on 2023-10-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_or_edge', models.TextField()),
                ('doc_id', models.BigIntegerField()),
                ('source_node', models.TextField()),
                ('target_node', models.TextField(blank=True, null=True)),
                ('relationship', models.TextField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
