# Generated by Django 5.2.4 on 2025-08-06 23:50

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apirequestlog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['query_params'], name='api_apirequ_query_p_b0f2a3_gin'),
        ),
    ]
