# Generated by Django 4.2.7 on 2023-12-28 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='trackedorganization',
            constraint=models.UniqueConstraint(models.F('user'), models.OrderBy(django.db.models.functions.text.Lower('organization_name')), name='trackeditems_unique_user_organization_name'),
        ),
    ]
