# Generated by Django 5.0 on 2024-01-01 11:32

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeditems', '0002_alter_trackedorganization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackedorganization',
            name='trackeditems_unique_user_organization_uri',
        ),
        migrations.AddConstraint(
            model_name='trackedorganization',
            constraint=models.UniqueConstraint(models.F('user'), models.OrderBy(django.db.models.functions.text.Lower('organization_uri'), descending=True), name='trackeditems_unique_user_organization_uri'),
        ),
    ]
