# Generated by Django 5.0.1 on 2024-04-08 20:15

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeditems', '0004_activitynotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedIndustryGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.TextField()),
                ('geo_code', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['industry_name', 'geo_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='trackedindustrygeo',
            constraint=models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('industry_name'), django.db.models.functions.text.Lower('geo_code'), name='trackedgeoindustry_unique_user_industry_geo'),
        ),
    ]
