# Generated by Django 5.1.4 on 2025-01-22 18:19

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeditems', '0005_trackedindustrygeo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_id', models.IntegerField()),
                ('industry_search_str', models.TextField()),
                ('region', models.TextField()),
                ('organization_uri', models.URLField()),
                ('trackable', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('user'), models.F('industry_id'), django.db.models.functions.text.Lower('region'), name='trackeditem_unique_user_industry_region'), models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('organization_uri'), name='trackeditem_unique_user_organization_uri'), models.UniqueConstraint(models.F('user'), django.db.models.functions.text.Lower('industry_search_str'), django.db.models.functions.text.Lower('region'), name='trackeditem_unique_user_search_str_region')],
            },
        ),
    ]
