# Generated by Django 5.1.4 on 2025-01-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeditems', '0006_trackeditem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackeditem',
            name='trackeditem_unique_user_industry_region',
        ),
        migrations.RemoveConstraint(
            model_name='trackeditem',
            name='trackeditem_unique_user_organization_uri',
        ),
        migrations.RemoveConstraint(
            model_name='trackeditem',
            name='trackeditem_unique_user_search_str_region',
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='industry_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='industry_search_str',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='organization_uri',
            field=models.URLField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='region',
            field=models.TextField(null=True),
        ),
    ]
