# Generated by Django 5.1.6 on 2025-02-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeditems', '0007_remove_trackeditem_trackeditem_unique_user_industry_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackeditem',
            name='and_similar_orgs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='industry_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='industry_search_str',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='organization_uri',
            field=models.URLField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='trackeditem',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
    ]
