# Generated by Django 4.2.7 on 2023-12-25 09:20

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trackedorganization',
            constraint=models.UniqueConstraint(models.F('user'), models.OrderBy(django.db.models.functions.text.Lower('organization_name')), name='unique_user_organization_name'),
        ),
    ]
