# Generated by Django 4.2.7 on 2023-12-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_trackedorganization_unique_user_organization_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackedorganization',
            options={'ordering': ['organization_name']},
        ),
    ]
